name: InfractionManager
version: 1.0.3-BETA
main: com.killerofpie.infractionmanager.InfractionManager

author: KillerOfPie
description: A plugin for server staff to track and manage players who break server rules.
website: https://www.spigotmc.org/resources/infractionmanager.52022/

commands:
  infraction:
    description: Core command for Infraction Manager
    aliases: [infractionmanager, ticket, im]